package chemicraft.lib;

/**
 * A lot are from Hippiecraft.
 */
public class Elements {
	
	/**
	 * A list of all elements sorted by atomic number.
	 */
	public static final String[] elements = {"hydrogen", "helium", "lithium", "beryllium",
		"boron", "carbon", "nitrogen", "oxygen", "fluorine", "neon", "sodium", "magnesium",
		"aluminium", "silicon", "phosphorus", "sulfur", "chlorine", "argon", "potassium",
		"calcium", "scandium", "titanium", "vanadium", "chromium", "manganese", "iron",
		"cobalt", "nickel", "copper", "zinc", "gallium", "germanium", "arsenic", "selenium",
		"bromine", "krypton", "rubidium", "strontium", "yttrium", "zirconium", "niobium",
		"molybdenum", "technetium", "ruthenium", "rhodium", "palladium", "silver", "cadmium",
		"indium", "tin", "antimony", "tellurium", "iodine", "xenon", "caesium", "barium",
		"lanthanum", "cerium", "praseodymium", "neodymium", "promethium", "samarium",
		"europium", "gadolinium", "terbium", "dysprosium", "holmium", "erbium", "thulium",
		"ytterbium", "lutetium", "hafnium", "tantalum", "tungsten", "rhenium", "osmium",
		"iridium", "platinum", "gold", "mercury", "thallium", "lead", "bismuth", "polonium",
		"astatine", "radon", "francium", "radium", "actinium", "thorium", "protactinium",
		"uranium", "neptunium", "plutonium", "americium", "curium", "berkelium",
		"californium", "einsteinium", "fermium", "mendelevium", "nobelium", "lawrencium",
		"rutherfordium", "dubnium", "seaborgium", "bohrium", "hassium", "meitnerium",
		"darmstadtium", "roentgenium", "copernicium", "ununtrium", "flerovium",
		"ununpentium", "livermorium", "ununseptium", "ununoctium"};
	
	/**
     * Atomic Numbers
     * 
     * Might come in handy in code to make things
     * clearer rather than just having "random"
     * numbers. Also just nice to have in one
     * place.
     * 
     */
    
    public static final int
    ID_ACTINIUM = 89,
    ID_ALUMINIUM = 13,
    ID_AMERICIUM = 95,
    ID_ANTIMONY = 51,
    ID_ARGON = 18,
    ID_ARSENIC = 33,
    ID_ASTATINE = 85,
    ID_BARIUM = 56,
    ID_BERKELIUM = 97,
    ID_BERYLLIUM = 4,
    ID_BISMUTH = 83,
    ID_BOHRIUM = 107,
    ID_BORON = 5,
    ID_BROMINE = 35,
    ID_CADMIUM = 48,
    ID_CAESIUM = 55,
    ID_CALCIUM = 20,
    ID_CALIFORNIUM = 98,
    ID_CARBON = 6,
    ID_CERIUM = 58,
    ID_CHLORINE = 17,
    ID_CHROMIUM = 24,
    ID_COBALT = 27,
    ID_COPERNICIUM = 112,
    ID_COPPER = 29,
    ID_CURIUM = 96,
    ID_DARMSTADTIUM = 110,
    ID_DUBNIUM = 105,
    ID_DYSPROSIUM = 66,
    ID_EINSTEINIUM = 99,
    ID_ERBIUM = 68,
    ID_EUROPIUM = 63,
    ID_FERMIUM = 100,
    ID_FLEROVIUM = 114,
    ID_FLUORINE = 9,
    ID_FRANCIUM = 87,
    ID_GADOLINIUM = 64,
    ID_GALLIUM = 31,
    ID_GERMANIUM = 32,
    ID_GOLD = 79,
    ID_HAFNIUM = 72,
    ID_HASSIUM = 108,
    ID_HELIUM = 2,
    ID_HOLMIUM = 67,
    ID_HYDROGEN = 1,
    ID_INDIUM = 49,
    ID_IODINE = 53,
    ID_IRIDIUM = 77,
    ID_IRON = 26,
    ID_KRYPTON = 36,
    ID_LANTHANUM = 57,
    ID_LAWRENCIUM = 103,
    ID_LEAD = 82,
    ID_LITHIUM = 3,
    ID_LIVERMORIUM = 116,
    ID_LUTETIUM = 71,
    ID_MAGNESIUM = 12,
    ID_MANGANESE = 25,
    ID_MEITNERIUM = 109,
    ID_MENDELEVIUM = 101,
    ID_MERCURY = 80,
    ID_MOLYBDENUM = 42,
    ID_NEODYMIUM = 60,
    ID_NEON = 10,
    ID_NEPTUNIUM = 93,
    ID_NICKEL = 28,
    ID_NIOBIUM = 41,
    ID_NITROGEN = 7,
    ID_NOBELIUM = 102,
    ID_OSMIUM = 76,
    ID_OXYGEN = 8,
    ID_PALLADIUM = 46,
    ID_PHOSPHORUS = 15,
    ID_PLATINUM = 78,
    ID_PLUTONIUM = 94,
    ID_POLONIUM = 84,
    ID_POTASSIUM = 19,
    ID_PRASEODYMIUM = 59,
    ID_PROMETHIUM = 61,
    ID_PROTACTINIUM = 91,
    ID_RADIUM = 88,
    ID_RADON = 86,
    ID_RHENIUM = 75,
    ID_RHODIUM = 45,
    ID_ROENTGENIUM = 111,
    ID_RUBIDIUM = 37,
    ID_RUTHENIUM = 44,
    ID_RUTHERFORDIUM = 104,
    ID_SAMARIUM = 62,
    ID_SCANDIUM = 21,
    ID_SEABORGIUM = 106,
    ID_SELENIUM = 34,
    ID_SILICON = 14,
    ID_SILVER = 47,
    ID_SODIUM = 11,
    ID_STRONTIUM = 38,
    ID_SULFUR = 16,
    ID_TANTALUM = 73,
    ID_TECHNETIUM = 43,
    ID_TELLURIUM = 52,
    ID_TERBIUM = 65,
    ID_THALLIUM = 81,
    ID_THORIUM = 90,
    ID_THULIUM = 69,
    ID_TIN = 50,
    ID_TITANIUM = 22,
    ID_TUNGSTEN = 74,
    ID_UNUNOCTIUM = 118,
    ID_UNUNPENTIUM = 115,
    ID_UNUNSEPTIUM = 117,
    ID_UNUNTRIUM = 113,
    ID_URANIUM = 92,
    ID_VANADIUM = 23,
    ID_XENON = 54,
    ID_YTTERBIUM = 70,
    ID_YTTRIUM = 39,
    ID_ZINC = 30,
    ID_ZIRCONIUM = 40;
    
    public String getElementName(int atomicNumber) {
    	return elements[atomicNumber - 1];
    }
    
}
